### ISSUE TITLE
how to train specialized question encoders?

### ISSUE THREAD

**Issue by wuyaoxuehun** [princeton-nlp/EntityQuestions#2]
Could you please elaborate on how you train the specialized question encoders?

**Comment by cdsciavolino** [comment]
Hi there, thanks for checking out our paper!

In this section, we consider a DPR model trained on a single dataset (in our paper, either Natural Questions or Probably Asked Questions) using the regular DPR training procedure. To create a specialized question encoder on a single domain, we consider a training/dev set for the new domain. We then fine-tune the existing model on the dataset for the new domain using the same DPR training procedure, but with the context encoder weights fixed. Specifically, we used a flag `--fix_ctx_encoder` in the DPR repo, which throws away any updates to the context encoder.
