### ISSUE TITLE
Aligned T-REx Samples

### ISSUE THREAD

**Issue by mleszczy** [princeton-nlp/EntityQuestions#3]
Hi, 

Thank you for sharing this interesting work! 

The paper mentions that the entity questions were created using triples from T-REx. Would it be possible to share the aligned T-REx samples for the questions? It could be useful to know the entities in the questions (e.g. to do similar analyses on entity statistics like in Figure 1 of the paper), as well as the corresponding evidence in Wikipedia (e.g. for mapping to knowledge bases like KILT). 

Thank you!

**Comment by cdsciavolino** [comment]
Hello - Thanks for checking out our paper!

When we sampled the original dataset, we did not keep the subject entity ids, and I believe it's imperfect to go back from label to id. We're looking into whether we can get them back through our original sampling code and I'll get back to you here!

**Comment by mleszczy** [comment]
That'd be awesome -- thanks!

**Comment by a3616001** [comment]
Hello @mleszczy ,

Please find EntityQuestions samples with aligned entities and evidence sentences [here](https://drive.google.com/file/d/1rmyMnG4cOpAq_dHyV36UEQpPpd5vBfTU/view?usp=sharing). 

Let us know if there is any issue!

**Comment by mleszczy** [comment]
Thank you! This is very helpful! 

Would it be possible to add the original doc id/QID that corresponds to the sentences (if you have it)? For instance in the example "Songwriting for Farmhouse was a joint effort between Trey Anastasio and Phish lyricist Tom Marshall..." the subject and object are Tom Marshall and Songwriting, but the original sentence seems to be from https://en.wikipedia.org/wiki/Farmhouse_(album). 

Thanks again for adding the evidence for the examples!

**Comment by a3616001** [comment]
Hi @mleszczy , I have added the corresponding doc id and title. Please check [here](https://drive.google.com/file/d/1RVxvCEW1IblFRYs94TR87kKohk_2jQfa/view?usp=sharing).

**Comment by mleszczy** [comment]
Thank you! This looks great! I really appreciate the fast response.
