### ISSUE TITLE
The dataset does not provide "positive paragraph context"

### ISSUE THREAD

**Issue by SunSiShining** [princeton-nlp/EntityQuestions#8]
Hi, the dataset does not provide "positive paragraph context".

Should we use has_answer_fn.py over the entire Wikipedia to create positive_ctxs?

**Comment by a3616001** [comment]
Hi, we provide the training/development sets with positive contexts (which we used for training the DPR model) for each relation [here](https://www.dropbox.com/sh/hjbyzhfn9hpx591/AABhDUzuTd8QAYZIZYpBu1GNa?dl=0).

We generated these files by using BM25 to get the top-100 contexts for each question in EntityQuestions, then bucketing positives/negatives using the `has_answer` functions.

Let me know if you have any further questions!

**Comment by SunSiShining** [comment]
Thank you for your help :D
